/*
 * flocking's service worker — GENERATED by amq/amq-flocking-build-sw, do not edit.
 *
 * Precaches the whole built site so the simulation runs offline once installed. Everything
 * is served cache-first; navigations fall back to the cached shell.
 *
 * Every asset is listed RELATIVE to this worker's scope: the site is published under a
 * subpath and an absolute path would miss.
 */
const CACHE = 'flocking-adda360b0908';
const ASSETS = [
  "assets/index-uCb8kxWC.js",
  "",
  "index.html"
];

const scoped = (path) => new URL(path, self.registration.scope).href;

// Cache tolerantly: one missing asset must not abort the whole batch.
function cacheAll(cache, urls) {
  return Promise.all(
    urls.map((url) =>
      cache.add(new Request(scoped(url), { cache: 'reload' })).catch(() => {}),
    ),
  );
}

self.addEventListener('install', (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE);
      await cacheAll(cache, ASSETS);
      await self.skipWaiting();
    })(),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      const keys = await caches.keys();
      await Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)));
      await self.clients.claim();
    })(),
  );
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET' || new URL(request.url).origin !== self.location.origin)
    return;

  event.respondWith(
    (async () => {
      const cached = await caches.match(request, { ignoreSearch: true });
      if (cached) return cached;

      try {
        const response = await fetch(request);
        if (response.ok) {
          const cache = await caches.open(CACHE);
          cache.put(request, response.clone());
        }
        return response;
      } catch {
        // Offline and uncached: a navigation still gets the shell, so the app boots.
        if (request.mode === 'navigate') {
          const shell = await caches.match(scoped(''));
          if (shell) return shell;
        }
        throw new Error('offline and not cached');
      }
    })(),
  );
});
